image: registry.gitlab.com/conoria/man_ccia:latest

pages:
  script:
  - R -q -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  - mv _book public
  artifacts:
    paths:
    - public
  only:
  - master
