{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-canadahcd
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/ConorIA/canadaHCD.git
  git_tag: patched
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - r-base
    - r-readr
    - r-tibble
    - r-curl
    - r-dplyr
    - r-zoo

  run:
    - r-base
    - r-readr
    - r-tibble
    - r-curl
    - r-dplyr
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('canadaHCD')"  # [not win]
    - "\"%R%\" -e \"library('canadaHCD')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/gavinsimpson/canadaHCD
  license: GPL-3
  summary: Access climate data from Government of Canada's Historical
    Climate Data API.
  license_family: GPL

# The original metadata for this package was:

# Package: canadaHCD
# Type: Package
# Title: Canadian Historical Climate Data
# Version: 0.0-1
# Date: 2016-05-26
# Authors@R: c(person(given = c("Gavin", "L."), family = "Simpson", role = c("aut","cre"), email = "ucfagls@gmail.com"), person(given = "Conor", family = "Anderson", role = "ctb"))
# Maintainer: Gavin L. Simpson <ucfagls@gmail.com>
# Description: Access climate data from Government of Canada's Historical Climate Data API.
# Depends: R (>= 2.10)
# Imports: readr, tibble, curl, dplyr, zoo, utils
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# License: GPL-3
# URL: https://github.com/gavinsimpson/canadaHCD/
# BugReports: https://github.com/gavinsimpson/canadaHCD/issues
# ByteCompile: true
# RoxygenNote: 6.0.1
# Author: Gavin L. Simpson [aut, cre],
# Conor Anderson [ctb]

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
