{% set version = '1.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-storr
  version: {{ version|replace("-", "_") }}

source:
  fn: storr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/storr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/storr/storr_{{ version }}.tar.gz


  sha256: ea158892713d430ad45c4cdd6ced812e93280d764568b099007ef8ed3c415267
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBI, RSQLite, RPostgres, knitr, mockr, progress, rbenchmark, testthat
requirements:
  build:
    - r-base
    - r-r6
    - r-digest

  run:
    - r-base
    - r-r6
    - r-digest

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('storr')"  # [not win]
    - "\"%R%\" -e \"library('storr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://richfitz.github.io/storr/
  license: MIT + file LICENSE
  summary: Creates and manages simple key-value stores.  These can
    use a variety of approaches for storing the data.  This package
    implements the base methods and support for file system, in-memory
    and DBI-based database stores.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: storr
# Title: Simple Key Value Stores
# Version: 1.2.0
# Description: Creates and manages simple key-value stores.  These can use a variety of approaches for storing the data.  This package implements the base methods and support for file system, in-memory and DBI-based database stores.
# Depends: R (>= 3.1.0)
# License: MIT + file LICENSE
# LazyData: true
# Authors@R: c(person("Rich", "FitzJohn", role = c("aut", "cre"), email = "rich.fitzjohn@gmail.com"))
# URL: https://github.com/richfitz/storr
# BugReports: https://github.com/richfitz/storr/issues
# Imports: R6 (>= 2.1.0), digest
# Suggests: DBI (>= 0.6), RSQLite (>= 1.1-2), RPostgres, knitr, mockr, progress, rbenchmark, testthat (>= 1.0.0)
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-05-31 07:18:55 UTC; rich
# Author: Rich FitzJohn [aut, cre]
# Maintainer: Rich FitzJohn <rich.fitzjohn@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-31 08:02:55 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
