{% set version = '0.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-canadahcdx
  version: {{ version|replace("-", "_") }}

source:
  git_url: git@gitlab.com:ConorIA/canadaHCDx.git
  git_tag: master
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - r-base
    - r-canadaHCD
    - r-curl
    - r-dplyr
    - r-geosphere
    - r-leaflet
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-storr
    - r-tibble
    - r-zoo

  run:
    - r-base
    - r-canadaHCD
    - r-curl
    - r-dplyr
    - r-geosphere
    - r-leaflet
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-storr
    - r-tibble
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('canadaHCDx')"  # [not win]
    - "\"%R%\" -e \"library('canadaHCDx')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://gitlab.com/ConorIA/canadaHCDx
  license: GPL-3
  summary: A number of functions to extend the useful canadaHCD package
    by Gavin L. Simposon (2016).
  license_family: GPL

# The original metadata for this package was:

# Package: canadaHCDx
# Type: Package
# Title: Additional functions for the canadaHCD package
# Version: 0.0.5
# Date: 2018-06-18
# Authors@R: c(person(given = c("Conor", "I."), family = "Anderson", role = c("aut","cre"), email = "conor.anderson@utoronto.ca"), person(given = c("William", "A."), family = "Gough", role = "ths", email = "gough@utsc.utoronto.ca"))
# Maintainer: Conor I. Anderson <conor@conr.ca>
# Description: A number of functions to extend the useful canadaHCD package by Gavin L. Simposon (2016).
# Depends: R (>= 3.1.0), canadaHCD
# Imports: curl, dplyr, geosphere, leaflet, rappdirs, readr, rlang, storr, tibble, zoo
# Suggests: Rdpack, testthat, covr
# Remotes: github::gavinsimpson/canadaHCD
# RdMacros: Rdpack
# License: GPL-3
# URL: https://gitlab.com/ConorIA/canadaHCDx/
# BugReports: https://gitlab.com/ConorIA/canadaHCDx/issues
# RoxygenNote: 6.0.1
# Author: Conor I. Anderson [aut, cre], William A. Gough [ths]

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
